// QA: record a stage playing in real time, then tile frames into a contact sheet. usage: node qa/sheet.mjs stage-2-transform.html 13 0.5
import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import fs from 'node:fs';
const [file, secs = '13', step = '0.5'] = process.argv.slice(2);
const base = path.basename(file, '.html');
const dir = 'qa/out/video-' + base; fs.rmSync(dir, { recursive: true, force: true }); fs.mkdirSync(dir, { recursive: true });
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 900, height: 645 }, recordVideo: { dir, size: { width: 900, height: 645 } } });
const page = await ctx.newPage();
await page.goto('file://' + path.resolve(file));
await page.waitForFunction(() => window.TL);
await page.evaluate(() => { TL.seek(0); TL.play(); });
await page.waitForTimeout(parseFloat(secs) * 1000);
await ctx.close(); await browser.close();
const webm = fs.readdirSync(dir).find((f) => f.endsWith('.webm'));
const ffmpeg = '/opt/pw-browsers/ffmpeg-1011/ffmpeg-linux';
const fps = 1 / parseFloat(step), n = Math.ceil(parseFloat(secs) / parseFloat(step));
const cols = 6, rows = Math.ceil(n / cols);
execFileSync(ffmpeg, ['-y', '-loglevel', 'error', '-i', `${dir}/${webm}`, '-vf', `fps=${fps},scale=300:-1,tile=${cols}x${rows}`, '-frames:v', '1', `qa/out/sheet-${base}.png`]);
console.log('wrote', `qa/out/sheet-${base}.png`);
